### ISSUE TITLE
Unable to resolve symbol 'doc' in social_news.clj file

### ISSUE THREAD

**Issue by dhruv-dave** [Datomic/day-of-datomic#15]
Not sure if this is an issue or I am misunderstanding something.
---
Looks like the namespace 'clojure.repl' should be required explicitly in social_news.clj file or evaluate (easy!) macro beofre any functions from clojure.repl ns are used. 
easy! macro is the one doing the requiring for clojure.repl ns (I am not really familiar with macros but we are doing (use 'datomic.samples.repl). clojure.repl should be loaded when (easy!) is called and not otherwise?)

; CIDER 0.7.0snapshot (package: 20140730.148) (Java 1.7.0_60, Clojure 1.6.0, nREPL 0.2.3, cider-nrepl 0.7.0-snapshot)
user> (use 'datomic.samples.repl)
nil
user> (doc easy!)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: doc in this context, compiling:(/private/var/folders/0f/4w3qyc8s5vs9bnv6lfh5pg_80000gn/T/form-init7212022613257498497.clj:1:1) 
user> (easy!)
:awesome
user> (doc easy!)
datomic.samples.repl/easy!
([])
Macro
  Set up a bunch of REPL conveniences. See the source
  with (source easy!) for details.
nil
user>

**Comment by benkamphaus** [comment]
Hi @dhruv-dave - thanks for reporting this issue. This issue is now out of date against the present code. -B
