### ISSUE TITLE
Error running "Hello World" example through REST API

### ISSUE THREAD

**Issue by psfblair** [Datomic/day-of-datomic#18]
In the REST API, I've transacted the "Hello World" datom as in hello_world.clj. If I then navigate to /api/query and put in the query

[:find ?e :where [?e :db/doc "Hello world"]]

I get a single result back. But if I add the "dot" for a single scalar binding, as is done on line 29 of hello_world.clj:

[:find ?e . :where [?e :db/doc "Hello world"]]

I get a 500 error from the server. I thought it might be an issue with URL-encoding--the "." stays as a dot rather than going to %2E--but changing that doesn't make a difference. I'm running Datomic 0.9.5344; I imagine this isn't an issue with the tutorial but thought I'd report it here first in case this is a "newbie issue." It's not entirely clear to me from the documentation what the single dot binding achieves.

**Comment by benkamphaus** [comment]
Hi @psfblair

At present, [find specifications](http://docs.datomic.com/query.html#find-specifications) other than relations (and also pull specifications) are not supported via Datomic's provided REST API. You'll need to use the relation form and handle the collection of tuples it returns (in this case the result set is a collection containing one tuple with a single element).

Best,
Ben
